name: My Principled Self
description: My mindset at work - briefly
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-time-machine
